version: '3.8'

services:
  redis-cache:
    image: redis:alpine
    container_name: user_redis_container
    ports:
      - "6379:6379"
    networks:
      - ms-network

  postgres-user:
    image: postgres:15
    container_name: user_db_container
    ports:
      - "5435:5432"
    environment:
      POSTGRES_DB: user_db
      POSTGRES_PASSWORD: 12345
    networks:
      - ms-network

  ms-user-service:
    build: .
    container_name: user_service
    ports:
      - "8081:8080"
    environment:
      DB_HOST: postgres-user
      DB_PORT: 5432
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 12345
      REDIS_HOST: redis-cache
      REDIS_PORT: 6379
    depends_on:
      - postgres-user
      - redis-cache
    networks:
      - ms-network

networks:
  ms-network:
    driver: bridge